[tools]
usage = "latest"
mani = "latest"
trivy = "latest"
chezmoi = "latest"
kubectl = "latest"
helm = "latest"
awscli = "latest"
python = "3.12.3"
task = "3.36.0"
terraform = "1.8.2"

[settings]
paranoid = true
