[tools]
usage = "latest"
opentofu = "latest"
mani = "latest"
trivy = "latest"
chezmoi = "latest"
kubectl = "latest"
helm = "latest"
awscli = "latest"
just = "latest"
python = "3.12.2"

[settings]
paranoid = true
